image: node:latest
# stages:
#   - npm
#   - lint
#   - test
#   - staging
#   - deployment

npm:client:
  tags:
    - node
  stage: npm
  artifacts:
    paths:
      - client/node_modules/
    expire_in: 1 days
    when: always
  script:
    - cd client/
    - echo "Running npm ci ..."
    - npm ci
  except:
    - /^back-feature.*$/
# lint client:
#   stage: lint
#   tags:
#     - node
#   script:
#     - cd client/
#     - echo "Linting.."
#     - npm run lint

# unit testing client:
#   stage: test
#   tags:
#     - node
#   script:
#     - cd client/
#     - echo "Running unit tests ..."
#     - ./node_modules/.bin/jest ./tests/unit/

# integration testing client:
#   stage: test
#   tags:
#     - node
#   variables:

#   script:
#     - cd client/
#     - echo "Running integration tests ..."
#     - ./node_modules/.bin/jest ./tests/integration/

staging:client:
  stage: staging client
  artifacts:
    paths:
      - server/public/
      - server/public/build
    expire_in: 1 week
  tags:
    - node
  script:
    - rm -rf server/public
    - mkdir server/public
    - cd client/

    # # - cd client/
    # #TODO: remove CI=false - so it treats warnings as errors again
    - CI=false npm run build
    - cd ../server
    - ls
    - cd public
    - ls
    - cd build/
    - ls

    # - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - development
