stages:
  - npm
  - lint
  - test
  - staging
  - deployment

npm client:
  tags:
    - stan
  stage: npm
  artifacts:
    paths:
      - client/node_modules/
    expire_in: 1 days
    when: always

  script:
    - cd client/
    - echo "Running npm ci ..."
    - npm ci
