stages:
  - npm
  - lint
  - test
  - staging
  - deployment

npm:
  tags:
    - stan
  stage: npm
  artifacts:
    paths:
      - node_modules
    expire_in: 1 days
    when: always

  script:
    - cd server/
    - npm ci

test:
     stage: test
     tags:
       - stan
     script:
       - cd server/
       - jest ./tests/unit/