stages:
  - npm
  - lint
  - test
  - staging client
  - staging server
  - deployment client
  - deployment server

include:
     - local: '/server/.gitlab-ci.yml'
     - local: '/client/.gitlab-ci.yml'