stages:
  - npm
  - lint
  - test
  - staging
  - deployment

npm:
  tags:
    - stan
  stage: npm
  artifacts:
    paths:
      - server/node_modules/
    expire_in: 1 days
    when: always

  script:
    - cd server/
    - echo "Running npm ci.."
    - npm ci

test:
  stage: test
  tags:
    - stan
  variables:
    ACCESS_TOKEN_SECRET: "(slkjdfpowefs-dopioufsdgsf$%&)sdlkngfsjdgsdf6573(45hru8§-§)$%lk4fwj9$3jhwo849ufepodv"
    REFRESH_TOKEN_SECRET: "klsd-jfoisjepeodfj!slkdghjsdg345678ceu-sdf2345§rhfs%%$%/(/&werldfgkhjkjpiodjfoieahf"
  script:
    - cd server/
    #  - echo "Running unit tests.."
    #  - jest ./tests/unit/
    - echo "Running integration tests.."
    - jest ./tests/integration/
