image: node:latest
stages:
  - npm
  - lint
  - test
  - staging
  - deployment

# before_script:
#   - apt-get update -qy
#   - apt-get install -y ruby-dev
#   - gem install dpl

npm:
  tags:
    - stan
  stage: npm
  artifacts:
    paths:
      - server/node_modules/
    expire_in: 1 days
    when: always

  script:
    - cd server/
    - echo "Running npm ci ..."
    - npm ci

# lint:
#   stage: lint
#   tags:
#     - stan
#   script:
#     - cd server/
#     - echo "Linting.."
#     - npm run lintFix

# unit testing:
#   stage: test
#   tags:
#     - stan
#   script:
#     - cd server/
#       - echo "Running unit tests ..."
#       - jest ./tests/unit/

# integration testing:
#   stage: test
#   tags:
#     - stan
#   variables:
#     ACCESS_TOKEN_SECRET: "(slkjdfpowefs-dopioufsdgsf$%&)sdlkngfsjdgsdf6573(45hru8§-§)$%lk4fwj9$3jhwo849ufepodv"
#     REFRESH_TOKEN_SECRET: "klsd-jfoisjepeodfj!slkdghjsdg345678ceu-sdf2345§rhfs%%$%/(/&werldfgkhjkjpiodjfoieahf"
#   script:
#     - cd server/
#     - echo "Running integration tests ..."
#     - jest ./tests/integration/

staging:
  stage: staging
  tags:
    - stan
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  # script:
  #   - echo "Staging deployment ..."
  #   # - git subtree push --prefix server/ stan-staging master
  #   # - apk update
  #   - apt-get update -qy
  #   - apt-get install -y ruby-dev
  #   - gem install dpl
  #   - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
