image: node:latest
stages:
  - npm
  - lint
  - test
  - staging
  - deployment

# before_script:
#   - apt-get update -qy
#   - apt-get install -y ruby-dev
#   - gem install dpl

npm server:
  tags:
    - stan
  stage: npm
  artifacts:
    paths:
      - server/node_modules/
    expire_in: 1 days
    when: always

  script:
    - cd server/
    - echo "Running npm ci ..."
    - npm ci
  except:
    - /^front-feature.*$/

# lint:
#   stage: lint
#   tags:
#     - stan
#   script:
#     - cd server/
#     - echo "Linting.."
#     - npm run lintFix

# unit testing:
#   stage: test
#   tags:
#     - stan
#   script:
#     - cd server/
#       - echo "Running unit tests ..."
#       - jest ./tests/unit/

# integration testing:
#   stage: test
#   tags:
#     - stan
#   variables:
#     ACCESS_TOKEN_SECRET: "(slkjdfpowefs-dopioufsdgsf$%&)sdlkngfsjdgsdf6573(45hru8§-§)$%lk4fwj9$3jhwo849ufepodv"
#     REFRESH_TOKEN_SECRET: "klsd-jfoisjepeodfj!slkdghjsdg345678ceu-sdf2345§rhfs%%$%/(/&werldfgkhjkjpiodjfoieahf"
#   script:
#     - cd server/
#     - echo "Running integration tests ..."
#     - jest ./tests/integration/

staging server:
  stage: staging
  tags:
    - stan
  image: ruby:latest
  script:
    # - apk update
    # - apk add ruby-dev
    # - brew update
    # - brew install rbenv rbenv-gem-rehash ruby-build
    # - gem install dpl
    - git remote -v
    # - brew install ruby
    # - sudo gem install dpl
    # - git remote remove stan-studyplan-staging

    # - git remote add staging-stan-studyplan https://heroku:$HEROKU_API_KEY@git.heroku.com/staging-stan-studyplan.git
    # git remote add stan-studyplan-staging https://heroku:$HEROKU_API_KEY@git.heroku.com/stan-studyplan-staging.git # works
    # - git remote add staging-stan-studyplan master git@heroku.com:staging-stan-studyplan.git #THIS WORKS
    # - git remote add stan-studyplan-staging master git@heroku.com:stan-studyplan-staging.git  #THIS WORKS
    # - git pull stan-studyplan-staging master
    # - git pull stan-studyplan-staging master --allow-unrelated-histories
    # - heroku git:clone -a myapp
    - heroku addons:create mongolab:sandbox --app staging-stan-studyplan
    - git subtree push --prefix server/ staging-stan-studyplan master
    - git remote -v
    # - cd server/
    # - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    # - git subtree push --prefix server/ stan-staging master
  only:
    - /^back-feature.*$/
    # - development
    # - master
  # script:
  #   - echo "Staging deployment ..."
  #   # - git subtree push --prefix server/ stan-staging master
  #   # - apk update
  #   - apt-get update -qy
  #   - apt-get install -y ruby-dev
  #   - gem install dpl
  #   - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
